# Generated by Django 3.2 on 2023-02-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_title_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='pub_date',
        ),
    ]
